name: BSkyBlock-Level
main: bskyblock.addin.level.Level
version: 0.1

authors: [tastybento]

depend: [BSkyBlock]

permissions:    
  bskyblock.intopten:
    description: Player is in the top ten.
    default: true